
version: "{build}-{branch}"
skip_tags: true
environment:
  global:
    STACK_ROOT: C:\sr

build: off

install:
  - curl -ostack.zip -L --insecure http://www.stackage.org/stack/windows-i386
  - 7z x stack.zip stack.exe
  - curl -ocef1750_win64.7z -L https://github.com/haskell-ui/cef3-raw/releases/download/1750win64/cef1750_win64.7z
  - 7z x cef1750_win64.7z
  - rename cef1750_win64 cef
  - dir

build_script:
  - stack setup --no-terminal > nul
  - stack build
